[tool.poetry]
name = "pyvdif"
version = "0.1.0"
description = "The Python3 package for VDIF (VLBI Data Interchange Format)"
readme = "README.md"
authors = ["scizorman <tueda1207@gmail.com>"]
repository = "https://github.com/scizorman/pyvdif"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
black = "^19.3b0"
flake8 = "^3.7"
mypy = "^0.711.0"
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
