version: 2.1

executors:
  default:
    working_directory: ~/project
    docker:
    - image: circleci/python:3.7
commands:
  restore_dependencies:
    steps:
      - restore_cache:
          name: Restore dependencies
          key: deps-{{ checksum "poetry.lock" }}
  save_dependencies:
    steps:
      - save_cache:
          name: Save dependencies
          key: deps-{{ checksum "poetry.lock" }}
          paths:
            - ~/.cache/pypoetry/virtualenvs

jobs:
  lint_and_test:
    executor:
      name: default
    steps:
      - checkout
      - restore_dependencies
      - run:
          name: Install dependencies
          command: poetry install
      - save_dependencies
      - run:
          name: Run test and report coverage
          command: |
            poetry run pytest --cov=pyvdif
            poetry run codecov

workflows:
  version: 2.1
  lint_and_test:
    jobs:
      - lint_and_test